fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    augeasproviders_core: "https://github.com/voxpupuli/puppet-augeasproviders_core.git"
    augeasproviders_shellvar: "https://github.com/voxpupuli/puppet-augeasproviders_shellvar.git"
    augeas_core:
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: "https://github.com/puppetlabs/puppetlabs-mount_core.git"
      puppet_version: ">= 6.0.0"
    transition: "https://github.com/puppetlabs/puppetlabs-transition.git"
  symlinks:
    "nfs": "#{source_dir}"
