# This is a shared config for easy consumption in other modules, without having
# to sync over a large file
require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  # Puppetserver 7 uses Jruby 9.3 which is compatible to C Ruby 2.6
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  Include:
    - '**/*.rb'
  Exclude:
    - files/**/*
    - vendor/**/*
    - .vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*
    - Gemfile
    - Rakefile
    - Guardfile
    - Vagrantfile
  NewCops: enable

Layout/ConditionPosition:
  Enabled: True

Lint/ElseLayout:
  Enabled: True

Lint/UnreachableCode:
  Enabled: True

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: True

Lint/EnsureReturn:
  Enabled: True

Lint/SuppressedException:
  Enabled: True

Lint/LiteralAsCondition:
  Enabled: True

Lint/ShadowingOuterLocalVariable:
  Enabled: True

Lint/LiteralInInterpolation:
  Enabled: True

Style/HashSyntax:
  Enabled: True

Style/RedundantReturn:
  Enabled: True

Layout/EndOfLine:
  Enabled: False

Lint/AmbiguousOperator:
  Enabled: True

Lint/AssignmentInCondition:
  Enabled: True

Layout/SpaceBeforeComment:
  Enabled: True

Style/AndOr:
  Enabled: True

Style/RedundantSelf:
  Enabled: True

Metrics/BlockLength:
  Enabled: False

# Method length is not necessarily an indicator of code quality
Metrics/MethodLength:
  Enabled: False

# Module length is not necessarily an indicator of code quality
Metrics/ModuleLength:
  Enabled: False

Style/WhileUntilModifier:
  Enabled: True

Lint/AmbiguousRegexpLiteral:
  Enabled: True

Security/Eval:
  Enabled: True

Layout/BlockAlignment:
  Enabled: True

Layout/DefEndAlignment:
  Enabled: True

Layout/EndAlignment:
  Enabled: True

Lint/DeprecatedClassMethods:
  Enabled: True

Lint/Loop:
  Enabled: True

Lint/ParenthesesAsGroupedExpression:
  Enabled: True

Lint/RescueException:
  Enabled: True

Lint/RedundantStringCoercion:
  Enabled: True

Lint/UnusedBlockArgument:
  Enabled: True

Lint/UnusedMethodArgument:
  Enabled: True

Lint/UselessAccessModifier:
  Enabled: True

Lint/Void:
  Enabled: True

Layout/AccessModifierIndentation:
  Enabled: True

Naming/AccessorMethodName:
  Enabled: True

Style/Alias:
  Enabled: True

Layout/ArrayAlignment:
  Enabled: True

Layout/HashAlignment:
  Enabled: True
  EnforcedHashRocketStyle: [key, table]
  EnforcedColonStyle: [key, table]

Layout/ParameterAlignment:
  Enabled: True

Metrics/BlockNesting:
  Enabled: True

Style/AsciiComments:
  Enabled: True

Style/Attr:
  Enabled: True

Style/CaseEquality:
  Enabled: True

Layout/CaseIndentation:
  Enabled: True

Style/CharacterLiteral:
  Enabled: True

Naming/ClassAndModuleCamelCase:
  Enabled: True

Style/ClassAndModuleChildren:
  Enabled: False

Style/ClassCheck:
  Enabled: True

# Class length is not necessarily an indicator of code quality
Metrics/ClassLength:
  Enabled: False

Style/ClassMethods:
  Enabled: True

Style/ClassVars:
  Enabled: True

Style/WhenThen:
  Enabled: True

Style/WordArray:
  Enabled: True

Style/RedundantPercentQ:
  Enabled: True

Layout/IndentationStyle:
  Enabled: True

Layout/SpaceBeforeSemicolon:
  Enabled: True

Layout/TrailingEmptyLines:
  Enabled: True

Layout/SpaceInsideBlockBraces:
  Enabled: True

Layout/SpaceBeforeBrackets:
  Enabled: True

Layout/SpaceInsideHashLiteralBraces:
  Enabled: True

Layout/SpaceInsideParens:
  Enabled: True

Layout/LeadingCommentSpace:
  Enabled: True

Layout/SpaceBeforeFirstArg:
  Enabled: True

Layout/SpaceAfterColon:
  Enabled: True

Layout/SpaceAfterComma:
  Enabled: True

Layout/SpaceAfterMethodName:
  Enabled: True

Layout/SpaceAfterNot:
  Enabled: True

Layout/SpaceAfterSemicolon:
  Enabled: True

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: True

Layout/SpaceAroundOperators:
  Enabled: True

Layout/SpaceBeforeBlockBraces:
  Enabled: True

Layout/SpaceBeforeComma:
  Enabled: True

Style/CollectionMethods:
  Enabled: True

Layout/CommentIndentation:
  Enabled: True

Style/ColonMethodCall:
  Enabled: True

Style/CommentAnnotation:
  Enabled: True

# 'Complexity' is very relative
Metrics/CyclomaticComplexity:
  Enabled: False

Naming/ConstantName:
  Enabled: True

Style/Documentation:
  Enabled: False

Style/DefWithParentheses:
  Enabled: True

Style/PreferredHashMethods:
  Enabled: True

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: True

Style/EachWithObject:
  Enabled: True

Layout/EmptyLineBetweenDefs:
  Enabled: True

Layout/FirstArrayElementIndentation:
  Enabled: True

Layout/FirstHashElementIndentation:
  Enabled: True

Layout/IndentationConsistency:
  Enabled: True

Layout/IndentationWidth:
  Enabled: True

Layout/EmptyLines:
  Enabled: True

Layout/EmptyLinesAroundAccessModifier:
  Enabled: True

Style/EmptyLiteral:
  Enabled: True

# Configuration parameters: AllowURI, URISchemes.
Layout/LineLength:
  Enabled: False

Style/MethodCallWithoutArgsParentheses:
  Enabled: True

Style/MethodDefParentheses:
  Enabled: True

Style/LineEndConcatenation:
  Enabled: True

Layout/TrailingWhitespace:
  Enabled: True

Style/StringLiterals:
  Enabled: True

Style/TrailingCommaInArguments:
  Enabled: True

Style/TrailingCommaInArrayLiteral:
  Enabled: False

Style/TrailingCommaInHashLiteral:
  Enabled: False

Style/GlobalVars:
  Enabled: True

Style/GuardClause:
  Enabled: True

Style/IfUnlessModifier:
  Enabled: True

Style/MultilineIfThen:
  Enabled: True

Style/NegatedIf:
  Enabled: True

Style/NegatedWhile:
  Enabled: True

Style/Next:
  Enabled: True

Style/SingleLineBlockParams:
  Enabled: True

Style/SingleLineMethods:
  Enabled: True

Style/SpecialGlobalVars:
  Enabled: True

Style/TrivialAccessors:
  Enabled: True

Style/UnlessElse:
  Enabled: True

Style/VariableInterpolation:
  Enabled: True

Naming/VariableName:
  Enabled: True

Style/WhileUntilDo:
  Enabled: True

Style/EvenOdd:
  Enabled: True

Naming/FileName:
  Enabled: True

Style/For:
  Enabled: True

Style/Lambda:
  Enabled: True

Naming/MethodName:
  Enabled: True

Style/MultilineTernaryOperator:
  Enabled: True

Style/NestedTernaryOperator:
  Enabled: True

Style/NilComparison:
  Enabled: True

Style/FormatString:
  Enabled: True

Style/MultilineBlockChain:
  Enabled: True

Style/Semicolon:
  Enabled: True

Style/SignalException:
  Enabled: True

Style/NonNilCheck:
  Enabled: True

Style/Not:
  Enabled: True

Style/NumericLiterals:
  Enabled: True

Style/OneLineConditional:
  Enabled: True

Naming/BinaryOperatorParameterName:
  Enabled: True

Style/ParenthesesAroundCondition:
  Enabled: True

Style/PercentLiteralDelimiters:
  Enabled: True

Style/PerlBackrefs:
  Enabled: True

Naming/PredicateName:
  Enabled: True
  AllowedMethods: ['is_a?', 'is_to_s']

Style/RedundantException:
  Enabled: True

Style/SelfAssignment:
  Enabled: True

Style/Proc:
  Enabled: True

Style/RaiseArgs:
  Enabled: True

Style/RedundantBegin:
  Enabled: True

Style/RescueModifier:
  Enabled: True

# based on https://github.com/voxpupuli/modulesync_config/issues/168
Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Enabled: True

Lint/UnderscorePrefixedVariableName:
  Enabled: True

Metrics/ParameterLists:
  Enabled: False

Lint/RequireParentheses:
  Enabled: True

Style/ModuleFunction:
  Enabled: True

Lint/Debugger:
  Enabled: True

Style/IfWithSemicolon:
  Enabled: True

Style/Encoding:
  Enabled: True

Style/BlockDelimiters:
  Enabled: True

Layout/MultilineBlockLayout:
  Enabled: True

# 'Complexity' is very relative
Metrics/AbcSize:
  Enabled: False

# 'Complexity' is very relative
Metrics/PerceivedComplexity:
  Enabled: False

Lint/UselessAssignment:
  Enabled: True

Layout/ClosingParenthesisIndentation:
  Enabled: True

# Boolean symbols are used quite extensively in Puppet types/providers
Lint/BooleanSymbol:
  Enabled: False

# RSpec

RSpec/BeforeAfterAll:
  Exclude:
    - spec/acceptance/**/*

# We don't use rspec in this way
RSpec/DescribeClass:
  Enabled: False

# Example length is not necessarily an indicator of code quality
RSpec/ExampleLength:
  Enabled: False

RSpec/NamedSubject:
  Enabled: False

# disabled for now since they cause a lot of issues
# these issues aren't easy to fix
RSpec/RepeatedDescription:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: True

Security/YAMLLoad:
  Enabled: True

# This affects hiera interpolation, as well as some configs that we push.
Style/FormatStringToken:
  Enabled: false

# This is useful, but sometimes a little too picky about where unit tests files
# are located.
RSpec/FilePath:
  Enabled: false

# Leaving these enabled creates too much busy work
RSpec/ContextWording:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: ['at', 'by', 'to', 'db', 'id', 'in', 'io', 'ip', 'of', 'on', 'os', 'pp', 'is']

# New cops available after rubocop upgrade
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: false
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true
Lint/AmbiguousRange: # new in 1.19
  Enabled: true
Lint/EmptyInPattern: # new in 1.16
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler: # new in 1.21
  Enabled: true
Lint/RequireRelativeSelfPath: # new in 1.22
  Enabled: true
Security/IoMethods: # new in 1.22
  Enabled: true
Style/InPatternThen: # new in 1.16
  Enabled: true
Style/MultilineInPatternThen: # new in 1.16
  Enabled: true
Style/NumberedParameters: # new in 1.22
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/QuotedSymbols: # new in 1.16
  Enabled: true
Style/RedundantSelfAssignmentBranch: # new in 1.19
  Enabled: true
Style/SelectByRegexp: # new in 1.22
  Enabled: true
Style/StringChars: # new in 1.12
  Enabled: true
RSpec/ExcessiveDocstringSpacing: # new in 2.5
  Enabled: true
RSpec/IdenticalEqualityAssertion: # new in 2.4
  Enabled: true
RSpec/SubjectDeclaration: # new in 2.5
  Enabled: true
RSpec/Rails/AvoidSetupHook: # new in 2.4
  Enabled: true
RSpec/ImplicitSubject:
  Enabled: false
# new configurations since rubocop 1.50.0
RSpec/NoExpectationExample:
  Enabled: false
inherit_gem:
  voxpupuli-test: rubocop.yml
