---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
env:
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES="yes" CHECK=test
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes" CHECK=test
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES="yes" CHECK=test
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 6.1" STRICT_VARIABLES="yes" CHECK=test
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 6.2" STRICT_VARIABLES="yes" CHECK=test
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes" CHECK=rubocop
    bundler_args: --without system_tests development
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=ubuntu-14.04
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=ubuntu-16.04
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_INSTALL_TYPE=agent BEAKER_set=ubuntu-18.04
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=centos-6
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=centos-7
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=debian-7
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=debian-8
    bundler_args: --without development
    script: bundle exec rake beaker
    services: docker
    sudo: required
  allow_failures:
    - env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES="yes" CHECK=test
    - env: PUPPET_VERSION="~> 6.1" STRICT_VARIABLES="yes" CHECK=test
    - env: PUPPET_VERSION="~> 6.2" STRICT_VARIABLES="yes" CHECK=test
notifications:
  email: false
